version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-job:
    executor:
      name: node/default
      tag: "latest"
    steps:
      - checkout
      - run: git config --global user.email "skxeve@gmail.com"
      - run: git config --global user.name "CircleCI"
      - run: git branch
      - run: if [ "$CIRCLE_BRANCH" != "master" ]; then git branch -D master && git checkout master && git merge $CIRCLE_BRANCH --no-edit; fi
      - node/with-cache:
          cache-version: v1
          steps:
            - run: npm -v
            - run: npm install
      - run: npm run build
      - run: git status
      - run: git add -A
      - run: git commit -m '[skip ci] npm run build by CircleCI.'
      - run: git push origin master
workflows:
  version: 2
  build-workflow:
    jobs:
      - build-job:
          filters:
            branches:
              only:
                - master
                - log
